### ISSUE TITLE
PHP Warning – yii\base\ErrorException after setting up

### ISSUE THREAD

**Issue by Saboteur777** [Rias500/craft-notifications#3]
Just got the error below. What am I missing? 

```
yii\base\ErrorException: Illegal string offset 'class' in /var/www/vendor/rias/craft-notifications/src/Notifications.php:89
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'Illegal string ...', '/var/www/vendor...', 89)
#1 /var/www/vendor/rias/craft-notifications/src/Notifications.php(89): craft\web\ErrorHandler->handleError(2, 'Illegal string ...', '/var/www/vendor...', 89, Array)
#2 /var/www/vendor/yiisoft/yii2/base/BaseObject.php(108): rias\notifications\Notifications->init()
#3 /var/www/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#4 /var/www/vendor/craftcms/cms/src/base/Plugin.php(88): yii\base\Module->__construct('notifications', Object(craft\web\Application), Array)
#5 [internal function]: craft\base\Plugin->__construct('notifications', Object(craft\web\Application), Array)
#6 /var/www/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#7 /var/www/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('rias\\notificati...', Array, Array)
#8 /var/www/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('rias\\notificati...', Array, Array)
#9 /var/www/vendor/craftcms/cms/src/services/Plugins.php(777): yii\BaseYii::createObject(Array, Array)
#10 /var/www/vendor/craftcms/cms/src/services/Plugins.php(196): craft\services\Plugins->createPlugin('notifications', Array)
#11 /var/www/vendor/craftcms/cms/src/base/ApplicationTrait.php(1195): craft\services\Plugins->loadPlugins()
#12 /var/www/vendor/craftcms/cms/src/web/Application.php(97): craft\web\Application->_init()
#13 /var/www/vendor/yiisoft/yii2/base/BaseObject.php(108): craft\web\Application->init()
#14 /var/www/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#15 /var/www/vendor/craftcms/cms/src/web/Application.php(85): yii\base\Application->__construct(Array)
#16 [internal function]: craft\web\Application->__construct(Array)
#17 /var/www/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#18 /var/www/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#19 /var/www/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#20 /var/www/vendor/craftcms/cms/bootstrap/bootstrap.php(243): yii\BaseYii::createObject(Array)
#21 /var/www/vendor/craftcms/cms/bootstrap/web.php(42): require('/var/www/vendor...')
#22 /var/www/html/index.php(20): require('/var/www/vendor...')
#23 {main}
```

**Comment by Rias500** [comment]
Could you post the exact code you’re using for your notifications?

**Comment by Saboteur777** [comment]
Wow, that was fast, sure! 

`notifications/KapcsolatfelvetelAdded.php`:
```
<?php

namespace app\notifications;

use Craft;
use craft\elements\Entry;
use craft\helpers\ArrayHelper;
use craft\mail\Message;
use rias\notifications\messages\SlackMessage;
use rias\notifications\models\Notification;

class KapcsolatfelvetelAdded extends Notification
{
    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($event = null)
    {
        parent::__construct($event);
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array
     */
    public function via()
    {
        $entry = $this->event->sender;

        if ($entry->section->handle === 'kapcsolatfelvetel' && !$this->event->isNew) {
            return [
                'mail' => 'otto@webmenedzser.hu',
            ];
        }

        return [];
    }

    public function toDatabase()
    {
        return ArrayHelper::toArray($this);
    }

    public function toSlack()
    {
        return (new SlackMessage)
            ->content("Hello world.");
    }

    public function toMail($notifiable)
    {
        $message = new Message();
        $message->setTo($notifiable);
        $message->setSubject("Új kapcsolatfelvétel érkezett!");
        $message->setHtmlBody("
            <p>{$title}</p>
        ");

        return $message;
    }
}
```

`config/notifications.php`:
```
<?php

return [
    /**
     * This is where you define your notifications for example if you want to trigger a notification
     * every time a blogpost is added, your notifications array could look like this:
    * 'notifications' => [
    *     [
    *         'elementType' => \craft\elements\Entry::class,
    *         'event' => \craft\elements\Entry::EVENT_AFTER_SAVE,
    *         'criteria' => [
    *             'section' => 'blog'
    *         ],
    *         'notification' => \app\notifications\BlogPostAdded::class,
    *     ],
    * ],
     *
     * In your BlogPostAdded class' via($event) function you could then check if the entry that was saved is a new entry
     * through the event properties
     */
    'notifications' => [
        'class' => \craft\elements\Entry::class,
        'event' => \craft\elements\Entry::EVENT_AFTER_SAVE,
        'notification' => \app\notifications\KapcsolatfelvetelAdded::class,
    ],
];
```

Just  tell me, if you need more info!

**Comment by Rias500** [comment]
Ah I see, you're missing an array level:

```
'notifications' => [
        'class' => \craft\elements\Entry::class,
        'event' => \craft\elements\Entry::EVENT_AFTER_SAVE,
        'notification' => \app\notifications\KapcsolatfelvetelAdded::class,
    ],
```

Should be:

```
'notifications' => [
        [
            'class' => \craft\elements\Entry::class,
            'event' => \craft\elements\Entry::EVENT_AFTER_SAVE,
            'notification' => \app\notifications\KapcsolatfelvetelAdded::class,
        ],
    ],
```

Because you can have multiple notifications. Let me know if this fixes it and if you experience any other issues.

**Comment by Saboteur777** [comment]
Thanks, that solved the problem!
